### ISSUE TITLE
Integrate Watch-Directory with Pester?

### ISSUE THREAD

**Issue by dfinke** [nightroman/PowerShelf#5]
Hello,

Wanted to get your thoughts, and maybe even convince you to implement it :-)

Your `Watch-Directory` is the most reliable one I've found.

I think it'd be great to wire into Pester. `Invoke-Pester -wait`. Along the lines of `npm compile wait`, in the node.js world.

Here's how I'm using it. I need to launch Pester in another PowerShell instance because it gets cranky that I'm using ps classes.

`Watch-Directory . -Command {PowerShell {Invoke-Pester -testname 'AppService Tests' } } -WaitSeconds 1 -TestSeconds 1 -Filter  *.ps1 -Recurse`

I have not analyzed Pester, seems like this may be an easy thing to bolt on.

Don't know if you've tried or might know of a better approach?

Thanks
Doug

**Comment by nightroman** [comment]
Hi Doug,

I am glad you found Watch-Directory useful and "the most reliable". I am not sure how I can help, though. I am not using Pester for testing. Invoke-Build is quite enough for me, and actually more useful due to available output from tests.

So please go ahead and if anything is needed from me/Watch-Directory then I will think of this.
