### ISSUE TITLE
How to handle multiple change notifications?

### ISSUE THREAD

**Issue by dfinke** [nightroman/PowerShelf#6]
Using `Watch-Directory.ps1`, I've seen discussions about `FileSystemWatcher` reporting multiple change events for a single file change. Any suggestions on how to process only one of these notifications at the PS level?

**Comment by nightroman** [comment]
The parameter `WaitSeconds` (default 5) is added in order to deal with this issue. We do not trigger the handler on any change. We wait for the moment when all changes and notifications are hopefully done.

Do you see the issue in practice? What are the scenario and the parameters?

In other words, I think you get what you ask out of the box. Or I misunderstand.

**Comment by dfinke** [comment]
Thanks. I had set the `-TestSeconds` and `-WaitSeconds` to the same amount of time. I bumped up `-WaitSeconds` and that looks like it stopped the reporting of two changed events.
